# Generated by Django 5.1.5 on 2025-02-02 11:31

import apps.shared.models
import apps.species.models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.shared.models.NameField(max_length=255, unique=True)),
                ('slug', apps.shared.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', models.ImageField(upload_to=apps.species.models.upload_bat_cover_image_to_func, verbose_name='Cover Image')),
                ('is_in_red_list', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.shared.models.NameField(max_length=255, unique=True)),
                ('slug', apps.shared.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ('name',),
            },
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BatAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('language', apps.shared.models.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English')], default='az', max_length=2)),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='species.bat')),
            ],
        ),
        migrations.CreateModel(
            name='BatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.species.models.upload_bat_image_to_func, verbose_name='Cover Image')),
                ('bat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='species.bat')),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.shared.models.NameField(max_length=255, unique=True)),
                ('slug', apps.shared.models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genuses', to='species.family')),
            ],
            options={
                'verbose_name': 'Genus',
                'verbose_name_plural': 'Genus',
                'ordering': ('name',),
            },
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bat',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bats', to='species.genus'),
        ),
    ]
