# Generated by Django 5.1.5 on 2025-02-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batattribute',
            options={'verbose_name': 'Bat Attribute', 'verbose_name_plural': 'Bat Attributes'},
        ),
        migrations.AlterModelOptions(
            name='batimage',
            options={'verbose_name': 'Bat Image', 'verbose_name_plural': 'Bat Images'},
        ),
    ]
