# Generated by Django 5.1.5 on 2025-01-31 14:30

import apps.species.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bat',
            name='cover_image',
            field=models.ImageField(upload_to=apps.species.models.upload_bat_cover_image_to_func, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='batimage',
            name='image',
            field=models.ImageField(upload_to=apps.species.models.upload_bat_image_to_func, verbose_name='Image'),
        ),
    ]
