# Generated by Django 5.1.5 on 2025-02-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_batattribute_options_alter_batimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bat',
            options={'ordering': ('name',), 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='batattribute',
            options={'verbose_name': 'Species Attribute', 'verbose_name_plural': 'Species Attributes'},
        ),
        migrations.AlterModelOptions(
            name='batimage',
            options={'verbose_name': 'Species Image', 'verbose_name_plural': 'Species Images'},
        ),
        migrations.AlterField(
            model_name='batimage',
            name='bat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='species.bat', verbose_name='Species'),
        ),
    ]
