# Generated by Django 5.1.5 on 2025-02-01 22:36

import apps.species.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_bat_cover_image_alter_batimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatAttributes',
            new_name='BatAttribute',
        ),
        migrations.AlterField(
            model_name='batimage',
            name='image',
            field=models.ImageField(upload_to=apps.species.models.upload_bat_image_to_func, verbose_name='Cover Image'),
        ),
    ]
