# Generated by Django 4.1.1 on 2022-10-16 06:32

import ckeditor_uploader.fields
import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('cover_image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
            },
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_images', to='activities.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('results', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_attributes', to='activities.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='activities.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attributes', to='activities.project')),
            ],
        ),
    ]
