# Generated by Django 4.1.1 on 2022-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
