# Generated by Django 4.1.1 on 2022-11-05 22:05

import administration.models
import core.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=administration.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=administration.models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectattributes',
            name='description',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectattributes',
            name='language',
            field=administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='name',
            field=administration.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='slug',
            field=administration.models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitevisitattributes',
            name='description',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitattributes',
            name='language',
            field=administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='sitevisitattributes',
            name='results',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisitimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
    ]
