# Generated by Django 4.1.1 on 2022-10-06 07:36

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cover_image',
            field=models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.CreateModel(
            name='SiteVisitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.project')),
            ],
        ),
    ]
