# Generated by Django 4.1.1 on 2022-10-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitimage',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_images', to='activities.sitevisit'),
        ),
    ]
