# Generated by Django 4.1.1 on 2022-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_project_slug_alter_sitevisit_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='results',
        ),
    ]
