# Generated by Django 4.1.1 on 2022-10-08 18:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_remove_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attributes', to='activities.project')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('results', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_attributes', to='activities.sitevisit')),
            ],
        ),
        migrations.RemoveField(
            model_name='sitevisitdescription',
            name='site_visit',
        ),
        migrations.RemoveField(
            model_name='sitevisitresults',
            name='site_visit',
        ),
        migrations.DeleteModel(
            name='ProjectDescription',
        ),
        migrations.DeleteModel(
            name='SiteVisitDescription',
        ),
        migrations.DeleteModel(
            name='SiteVisitResults',
        ),
    ]
