# Generated by Django 5.1.5 on 2025-02-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
