# Generated by Django 4.1.1 on 2022-10-05 18:42

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
    ]
