# Generated by Django 4.1.1 on 2022-11-05 22:05

import administration.models
import core.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=administration.models.NameField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='authorattributes',
            name='description',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorattributes',
            name='language',
            field=administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='authorattributes',
            name='name',
            field=administration.models.NameField(max_length=200, unique=True),
        ),
    ]
