# Generated by Django 4.1.1 on 2022-10-15 06:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_author_description_remove_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorattributes',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
