# Generated by Django 4.1.1 on 2022-10-15 06:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_authorattributes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorattributes',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
