# Generated by Django 5.1.5 on 2025-02-03 17:01

import apps.shared.models
import django.db.models.manager
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Title')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about', 'About'), ('privacy_policy', 'Privacy Policy')], max_length=50, verbose_name='Key')),
                ('language', apps.shared.models.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English')], default='az', max_length=2)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Static Text',
                'verbose_name_plural': 'Static Texts',
                'unique_together': {('key', 'language')},
            },
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
