# Generated by Django 5.1.5 on 2025-02-02 12:22

import apps.shared.models
import django.db.models.manager
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about', 'About'), ('privacy_policy', 'Privacy Policy')], max_length=50)),
                ('language', apps.shared.models.LanguageField(choices=[('az', 'Azerbaijani'), ('en', 'English')], default='az', max_length=2)),
                ('content', tinymce.models.HTMLField()),
            ],
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
