# Generated by Django 5.1.5 on 2025-02-08 12:25

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carouselitem_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to=apps.home.models.upload_carousel_item_image_to_func, verbose_name='Image'),
        ),
    ]
