# Generated by Django 4.1.1 on 2022-10-04 08:18

import ckeditor.fields
import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='bats.family')),
            ],
            options={
                'verbose_name_plural': 'Genus',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('cover_image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('distribution', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('biology', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conservation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('habitat', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('threats', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_red_book', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genus', to='bats.genus')),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.helpers.uploadImageLocation)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bats.species')),
            ],
        ),
    ]
