# Generated by Django 4.1.1 on 2022-11-05 22:05

import administration.models
import core.helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=administration.models.NameField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=administration.models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=administration.models.NameField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genus',
            name='slug',
            field=administration.models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='cover_image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=administration.models.NameField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=administration.models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='biology',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='conservation',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='description',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='distribution',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='habitat',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='language',
            field=administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='speciesattributes',
            name='threats',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesimage',
            name='image',
            field=administration.models.ImageField(upload_to=core.helpers.uploadImageLocation),
        ),
        migrations.AlterField(
            model_name='speciesredbook',
            name='description',
            field=administration.models.RichTextEditorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciesredbook',
            name='language',
            field=administration.models.LanguageField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2),
        ),
    ]
