# Generated by Django 4.1.1 on 2022-10-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0002_alter_species_biology_alter_species_conservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesimage',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_images', to='bats.species'),
        ),
    ]
