# Generated by Django 4.1.1 on 2022-10-08 17:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0003_alter_speciesimage_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='biology',
        ),
        migrations.RemoveField(
            model_name='species',
            name='conservation',
        ),
        migrations.RemoveField(
            model_name='species',
            name='description',
        ),
        migrations.RemoveField(
            model_name='species',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='species',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='species',
            name='threats',
        ),
        migrations.CreateModel(
            name='SpeciesThreats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threats', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_threats', to='bats.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_habitat', to='bats.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_distribution', to='bats.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_description', to='bats.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesConservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conservation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_conservation', to='bats.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesBiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biology', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_biology', to='bats.species')),
            ],
        ),
    ]
