# Generated by Django 4.1.1 on 2022-10-08 18:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0004_remove_species_biology_remove_species_conservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('habitat', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('threats', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('distribution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('conservation', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('biology', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_attributes', to='bats.species')),
            ],
        ),
        migrations.RemoveField(
            model_name='speciesconservation',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesdescription',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesdistribution',
            name='species',
        ),
        migrations.RemoveField(
            model_name='specieshabitat',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesthreats',
            name='species',
        ),
        migrations.DeleteModel(
            name='SpeciesBiology',
        ),
        migrations.DeleteModel(
            name='SpeciesConservation',
        ),
        migrations.DeleteModel(
            name='SpeciesDescription',
        ),
        migrations.DeleteModel(
            name='SpeciesDistribution',
        ),
        migrations.DeleteModel(
            name='SpeciesHabitat',
        ),
        migrations.DeleteModel(
            name='SpeciesThreats',
        ),
    ]
