# Generated by Django 4.1.1 on 2022-10-15 09:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0005_speciesattributes_remove_speciesconservation_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesRedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=2)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_red_book', to='bats.species')),
            ],
        ),
    ]
