# Generated by Django 5.1.5 on 2025-01-31 14:30

import apps.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(upload_to=apps.activities.models.upload_project_cover_image_to_func, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='cover_image',
            field=models.ImageField(upload_to=apps.activities.models.upload_site_visit_cover_image_to_func, verbose_name='Cover Image'),
        ),
    ]
